name: Criar APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Instalar dependências do sistema
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            cmake \
            libffi-dev \
            libssl-dev

      - name: Instalar Buildozer
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install buildozer==1.5.0 cython==0.29.33

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      - name: Instalar ferramentas Android
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-33"
          sdkmanager "build-tools;33.0.2"
          sdkmanager "ndk;25.2.9519653"

      - name: Ajustar Buildozer SPEC
        run: |
          sed -i 's/^android.api = .*/android.api = 33/' buildozer.spec || true
          sed -i 's/^android.minapi = .*/android.minapi = 21/' buildozer.spec || true
          sed -i 's/^android.ndk = .*/android.ndk = 25.2.9519653/' buildozer.spec || true
          sed -i 's/^android.archs = .*/android.archs = arm64-v8a/' buildozer.spec || true
          sed -i 's/^requirements = .*/requirements = python3,kivy,pillow,reportlab/' buildozer.spec || true

      - name: Gerar APK
        run: |
          
          buildozer android debug

      - name: Enviar APK
        uses: actions/upload-artifact@v4
        with:
          name: zincotech-apk
          path: bin/*.apk
