name: Criar APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git zip unzip
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Instalar Android SDK
        uses: android-actions/setup-android@v3

      - name: Instalar Build Tools Compatíveis
        run: |
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-33"
          sdkmanager "build-tools;33.0.0"
          yes | sdkmanager --licenses

      - name: Gerar APK
        run: |
          yes | buildozer android debug

      - name: Enviar APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
